=== RunCor399/Distributed_Systems_Programming_Exam_Project/JSON Schemas/draft_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id" : "http://www.my-schema.com/draft_schema.json",
    "title": "Draft",
    "description": "JSON Schema that represents a Review Draft",
    "type": "object",
    "additionalProperties": false,
    "properties": {
        "$schema": {
            "type": "string",
            "description": "path to the JSON Schema to use for the validation of the data structure"
        },
        "draftId": {
            "type": "integer",
            "description": "unique identifier of the draft"
        },
        "filmId": {
            "type": "integer",
            "description": "unique identifier of the film for which this draft review was created"
        },
        "reviewId": {
            "type": "integer",
            "description": "unique identifier of the review for which the draft was created"
        },
        "rating": {
            "type": "integer",
            "description": "the rating the reviewer has given to the film",
            "minimum": 1,
            "maximum": 10
        },
        "review": {
            "type": "string",
            "description": "a textual description of the review",
            "maxLength": 1000
        },
        
        "author": {
            "oneOf": [
                {
                    "type": "integer",
                    "description": "unique identifier of the user that created this draft"
                },
                {
                    "type": "string",
                    "format": "uri",
                    "description": "uri to the user that created the draft"
                }
            ]     
        },
        "status": {
            "type": "boolean",
            "description": "true if the draft is open, false otherwise",
            "default": "true"
        },
        "votes": {
            "type": "array",
            "items": {
                "$ref": "./vote_schema.json"
            },
            "uniqueItems": true
        }
    }
}

=== RunCor399/Distributed_Systems_Programming_Exam_Project/JSON Schemas/json_examples/draft01.json
{
    "$schema": "../draft_schema.json",
    "draftId": 1,
    "filmId": 2,
    "reviewId": 1,
    "rating": 7,
    "review": "Non molto interessante.",
    "author": "http://film-library.com/api/users/1",
    "status": true,
    "votes": [
                {
                    "userId":"http://film-library/api/users/2",
                    "vote": true
                },
                {
                    "userId":"http://film-library/api/users/3",
                    "vote": false
                }
            ]
  }
