=== RunCor399/Distributed_Systems_Programming_Exam_Project/JSON Schemas/review_response_schema_v2.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id" : "http://www.my-schema.com/review_schema.json",
    "title": "Review Response",
    "description": "JSON Schema that represents reviews as they are returned from the backend",
    "type": "object",
    "additionalProperties": false,
    "properties": {
      "$schema": {
        "type": "string",
        "description": "path to the JSON Schema to use for the validation of the data structure"
      },
      "filmLink": {
        "type": "string",
        "format": "uri",
        "default": "/api/films/public/2",
        "description": "link to the film for which a new review has been created"
      },
      "filmId": {
        "type": "integer",
        "default": 2
      },
      "reviewId": {
        "type": "integer",
        "description": "unique identifier of the review",
        "default": 1
      },
      "review_type": {
        "type": "string",
        "enum": ["single", "coop"],
        "default": "coop"
      },
      "reviewers": {
        "type": "array",
        "items": {
          "type": "string",
          "format": "uri",
          "default": "/api/users/1"
        },
        "uniqueItems": true,
        "minItems": 1
      },
      "completed": {
        "type": "boolean",
        "description": "true if the review has been completed, false otherwise",
        "default": "false"
      },  
      "reviewDate": {
        "type": "string",
        "format": "date",
        "description": "the date when the review has been completed by the invited user"
      },
      "rating": {
        "type": "integer",
        "description": "the rating the reviewer has given to the film",
        "minimum": 1,
        "maximum": 10
      },
      "review": {
        "type": "string",
        "description": "a textual description of the review",
        "maxLength": 1000
      },
      "self": {
        "type": "string",
        "description": "link to this review",
        "format": "uri",
        "default": "/api/films/public/2/reviews/1"
      },
      "draftsLink": {
        "type": "string",
        "description": "link to drafts of this review",
        "format": "uri",
        "default": "/api/films/public/2/reviews/1/drafts"
      }
    },
    "required": ["filmId", "reviewId", "reviewers"],
    "if": {
      "properties": { "review_type": { "const": "coop" } }
    },
    "then": {
      "not": {
          "properties": { "completed": { "const": true } }
        },
      "required": ["draftsLink"]
    },
    "dependencies": {
      "completed": {
        "oneOf": [
          {
            "properties": {
              "completed": {
                "const": false
              }
            },
            "allOf" : [   
              {"not" : { "required" : ["reviewDate"] } },  
              {"not" : { "required" : ["rating"] } },
              {"not" : { "required" : ["review"] } }
            ]
          },
          {
            "properties": {
              "completed": {
                "const": true  
              }
            },
            "required": [
              "reviewDate", "rating", "review"
            ]
          }
        ]
      },
      "reviewDate": ["completed"],
      "rating": ["completed"],
      "review": ["completed"]
    }
  }

=== RunCor399/Distributed_Systems_Programming_Exam_Project/JSON Schemas/json_examples/review_response01.json
[
    {
        "$schema": "../review_response_schema.json",
        "filmId": 1,
        "reviewId": 1,
        "reviewers": ["http://film-library.com/api/users/1", "http://film-library.com/api/users/2"],
        "completed": true,
        "reviewDate": "2022-02-22",
        "review_type": "single",
        "rating": 4,
        "review": "Non molto interessante.",
        "self": "http://film-library.com/api/films/public/2/reviews/1",
        "draftsLink": "http://film-library.com/api/films/public/2/reviews/1/drafts"
    },
    {
        "$schema": "./review_response_schema.json",
        "filmId": 1,
        "reviewId": 1,
        "reviewers": ["http://film-library.com/api/users/1", "http://film-library.com/api/users/2"],
        "completed": false,
        "review_type": "coop",
        "self": "http://film-library.com/api/films/public/2/reviews/1",
        "draftsLink": "http://film-library.com/api/films/public/2/reviews/1/drafts"
    }
]
